FROM ruby:2.2.2

RUN apt-get update -y && apt-get upgrade -y
RUN gem install rails -v 4.2.4
RUN apt-get install nodejs -y

ONBUILD COPY app /opt/app

ONBUILD WORKDIR /opt/app

ONBUILD RUN bundle install
ONBUILD RUN rake db:migrate
ONBUILD RUN rake db:seed
